---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: aboussarsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        #env:
        #- name: MONGO_INITDB_ROOT_USERNAME
        #  value: "root"       # MongoDB root username
        #- name: MONGO_INITDB_ROOT_PASSWORD
        #  value: "example"    # MongoDB root password
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: aboussarsar
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017