---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb-deployment
  namespace: aboussarsar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: azizboussarsar/web_with_db:2
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service.aboussarsar.svc.cluster.local:27017/" # MongoDB URL from environment
        - name: MONGO_DB_NAME
          value: "flask_with_db"  # MongoDB database name
        - name: MONGO_COLLECTION_NAME
          value: "requests"      # MongoDB collection name
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: aboussarsar
spec:
  type: ClusterIP
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000