apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: {{ .Release.Namespace }}
data:
  MONGO_HOSTNAME: {{ .Values.webdb.mongo.hostname }}
  MONGO_PORT: "{{ .Values.webdb.mongo.port }}"
